build(python): add installation scripts

diff --git a/python/scripts/install b/python/scripts/install
--- a/python/scripts/install
+++ b/python/scripts/install
@@ -1,63 +1,30 @@
-#!/usr/bin/env python3
-import sys
-from shutil import which
-from subprocess import run as run_default
-from pathlib import Path
-import tomllib
+#!/usr/bin/bash
+error(){
+    echo "install error:" "$@" >&2
+    exit 1
+}
 
+run(){
+    echo "install:" "$@"
+    "$@"
+}
 
-ROOT = Path(__name__).parent.parent
-DIST_PATH = ROOT / "dist"
+for program in python poetry pipx; do
+    if ! command -v "$program" >/dev/null 2>&1; then
+        echo "required: $program" >&2
+        missing=1
+    fi
+done
+[[ -z "$missing" ]] || exit 1
 
+ROOT_DIR=$(dirname "$(dirname "$(realpath "$0")")")
+cd "$ROOT_DIR" || error "error finding project root"
+[[ -d ./dist ]] && rm -rf ./dist
+run poetry install --only main
+run poetry build --format sdist -o ./dist
 
-def run(*args: str, **kwargs):
-    run_default(args, stdout=sys.stdout, stderr=sys.stderr, check=True, cwd=ROOT, **kwargs)
+TARGZ=$(find ./dist -mindepth 1 -maxdepth 1 -name '*tar.gz' -print -quit)
+[[ -r "$TARGZ" ]] || error "somehow the tarball was lost"
+run pipx install "$TARGZ"
 
-
-def deep_get(dictionary: dict, *keys: str, default=None) -> any:
-    for key in keys:
-        try:
-            dictionary = dictionary[key]
-        except:
-            return default
-    return dictionary
-
-
-def require(*programs: str):
-    missing = False
-    for program in programs:
-        if which(program) is None:
-            print(f"required: {program}", file=sys.stderr)
-            missing = True
-
-    if missing:
-        sys.exit(1)
-
-
-def dist_file() -> Path:
-    with Path(ROOT / "pyproject.toml").open("rb") as f:
-        conf = tomllib.load(f)
-    
-    pkg_name = deep_get(conf, "tool", "poetry", "name")
-    version = deep_get(conf, "tool", "poetry", "version")
-
-    if type(pkg_name) is not str or type(version) is not str:
-        print(f"tool.poetry.name or tool.poetry.version missing in {ROOT/"pyproject.toml"}", file=sys.stderr)
-        sys.exit(1)
-    
-    return DIST_PATH / f"{pkg_name}-{version}.tar.gz"
-
-
-def main():
-    require("python3", "pip3", "poetry")
-
-    dist = dist_file()
-    run("poetry", "install")
-    run("poetry", "build", "--format", "sdist", "--output", DIST_PATH)
-    run("pip", "install", dist)
-
-    print("Installation succesful!")
-    
-
-if __name__ == '__main__':
-    main()
+echo "install: Installation complete!"
